spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=UTF-8&&serverTimezone=UTC
    username: root
    password: jiajia0930
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    root: info
    com.demo.blog: debug
  file:
    name: log/blog-dev.log

server:
  port: 8080
