spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=UTF-8&&serverTimezone=UTC
    username: root
    password: jiajia0930
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    root: wran
    com.demo.blog: info
  file:
    name: log/blog-prod.log


server:
  port: 8081
  servlet:
    context-path: /prod
